# -*- coding: utf-8 -*-
"""crawlsite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDlWoTe4aOx6AfFV_1y4_lwMa3ttv4_8
"""

# pip install langchain>=1.0.0 langchain-core>=1.0.0 langchain-community>=0.4.0 langchain-groq>=1.0.0 langchain-chroma>=1.0.0 chromadb>=0.4.24 fastembed>=0.2.6 streamlit>=1.32.0 beautifulsoup4>=4.12.3 python-dotenv>=1.0.1 pandas>=2.2.1

# pip install -q \
#   litellm \
#   wikipedia \
#   langchain \
#   langchain-groq \
#   langchain_community \
#   langchain-qdrant \
#   langchain_core \
#   fastembed \
#   flashrank \
#   pypdf

from langchain_community.document_loaders import PyPDFLoader
from fastembed import TextEmbedding
from langchain_community.embeddings import FastEmbedEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from langchain_groq import ChatGroq
from langchain_community.document_compressors import FlashrankRerank
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_classic.chains import create_history_aware_retriever,create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate
from langchain_classic.chains import create_history_aware_retriever,create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import MessagesPlaceholder
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.globals import set_verbose,set_debug

from langchain_qdrant import QdrantVectorStore

from langchain_community.document_loaders import WebBaseLoader
import bs4

URLS_TO_CRAWL = [
    "https://www.rvitm.edu.in/"
    "https://www.rvitm.edu.in/computer-science-engineering/",     # Placeholder for About page
    "https://www.rvitm.edu.in/computer-science-and-engineering-ai-ml/",# Placeholder for Admissions
    "https://www.rvitm.edu.in/admission/"    # Placeholder for Contact
]

loader = WebBaseLoader(
            web_paths=URLS_TO_CRAWL,
            bs_kwargs=dict(
                parse_only=bs4.SoupStrainer(
                    ["h1", "h2", "h3","h4","h5","h6", "p", "li","section"] # Typical tags containing useful content
                )
            )
        )
docs = loader.load()

for doc in docs:
    print("-"*50)
    print(doc.metadata)
    print(doc.page_content)
    print("\n\n")

textsplitter = RecursiveCharacterTextSplitter(chunk_size=2048, chunk_overlap=128)
split_docs = textsplitter.split_documents(docs)
print(f"Total pdf documents {len(docs)}")
print(f"Document chunks {len(split_docs)}")

embeddings = FastEmbedEmbeddings()
#vector_store = FAISS.from_documents(split_docs,embeddings)
vectorstore = QdrantVectorStore.from_documents(
    split_docs,
    embedding=embeddings,
    path="./collage2_db",   # local database
    collection_name="demo",
)

# try retrieving the documents
retriever = vectorstore.as_retriever(search_kwargs={'k': 5})
retrieved_docs = retriever.invoke('Computer science')
for doc in retrieved_docs:
  print(doc.metadata)
  print(doc.page_content)
  print("-" * 50)
  print()

llm=ChatGroq(model_name='llama-3.1-8b-instant',temperature=0,api_key=" put your api key ")


# Create qa chain and ask the question
from langchain_core.globals import set_verbose,set_debug
system_prompt = (
    "Use provided information to answer the user questions."
    "If you don't find the answer do not try to answer, just respond with \"Sorry! I don't know\""
    "Answer the question based on the provided context. Format the response for easy reading."
    "If the question doesnot have the section name then you have to get the section name from the number by retrieving first 50 documents which has titles"
    "don't know. Use three sentences maximum and keep the answer concise"
    ""
    "\n\n"
    "{context}"
)

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        ("human", "{input}"),
    ]
)

question_answer_chain = create_stuff_documents_chain(llm, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

rag_chain.invoke(
    {"input": "does it offer computer science "}
)["answer"]


# # ask question wrt to the previous answer
# conversational_rag_chain.invoke(
#     {"input": "what is teh eligibility crieatia"},
#     config={"configurable": {"session_id": "abc123"}},
# )["answer"]